### ISSUE TITLE
Maintenance is slow 

### ISSUE THREAD

**Issue by horaciocome1** [mozdevz/opensource#2]
There are pending pull requests for days.

**Comment by thatfiredev** [comment]
@horaciocome1 Thanks for bringing this up. The main reason why we haven't yet added any repositories is because we're not yet sure how to organize them.

One suggestion would be to group them by platform (Android, iOS, Web, Desktop, IoT, Cloud, etc), but then how would we display multi-platform projects?

Another suggestion would be grouping them by language(Java, Python, C++, etc).

Feel free to add any suggestions.

**Comment by thatfiredev** [comment]
We ended up organizing the repositories in alphabetical order, inspired by [acekyd/made-in-nigeria](https://github.com/acekyd/made-in-nigeria/).

Expect maintenance to be quicker now :)
